dist: xenial

language: python

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py36-django22 REQUIREMENTS=django_2_2.in
    python: 3.6
  - env: TOX_ENV=py37-django22 REQUIREMENTS=django_2_2.in
    python: 3.7
  - env: TOX_ENV=py38-django22 REQUIREMENTS=django_2_2.in
    python: 3.8
  - env: TOX_ENV=py39-django22 REQUIREMENTS=django_2_2.in
    python: 3.9

  - env: TOX_ENV=py36-django30 REQUIREMENTS=django_3_0.in
    python: 3.6
  - env: TOX_ENV=py37-django30 REQUIREMENTS=django_3_0.in
    python: 3.7
  - env: TOX_ENV=py38-django30 REQUIREMENTS=django_3_0.in
    python: 3.8
  - env: TOX_ENV=py39-django30 REQUIREMENTS=django_3_0.in
    python: 3.9

  - env: TOX_ENV=py36-django31 REQUIREMENTS=django_3_1.in
    python: 3.6
  - env: TOX_ENV=py37-django31 REQUIREMENTS=django_3_1.in
    python: 3.7
  - env: TOX_ENV=py38-django31 REQUIREMENTS=django_3_1.in
    python: 3.8
  - env: TOX_ENV=py39-django31 REQUIREMENTS=django_3_1.in
    python: 3.9

  - env: TOX_ENV=py36-django32 REQUIREMENTS=django_3_2.in
    python: 3.6
  - env: TOX_ENV=py37-django32 REQUIREMENTS=django_3_2.in
    python: 3.7
  - env: TOX_ENV=py38-django32 REQUIREMENTS=django_3_2.in
    python: 3.8
  - env: TOX_ENV=py39-django32 REQUIREMENTS=django_3_2.in
    python: 3.9

before_install:
  - pip install pip-tools
  - pip-compile examples/requirements/$REQUIREMENTS

install:
  - pip-compile examples/requirements/test.in
  - pip install -r examples/requirements/test.txt

before_script:
  - sleep 10

script: travis_retry tox -e $TOX_ENV

after_success:
  - pip install coveralls
  - coveralls
