[tox]
envlist =
    py{39,310,311,312,313}-django{42,51,52}

[testenv]
envlogdir =
    examples/logs/
    examples/db/
passenv = *
allowlist_externals = *
deps =
    django42: -r{toxinidir}/examples/requirements/django_4_2.txt
    django51: -r{toxinidir}/examples/requirements/django_5_1.txt
    django52: -r{toxinidir}/examples/requirements/django_5_2.txt
commands =
    coverage erase
    pip install -e .
    pytest -vvv

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
