name: test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:

          - python-version: '3.9'
            requirements: django_4_2
            tox_env: py39-django42
          - python-version: '3.10'
            requirements: django_4_2
            tox_env: py310-django42
          - python-version: '3.11'
            requirements: django_4_2
            tox_env: py311-django42
          - python-version: '3.12'
            requirements: django_4_2
            tox_env: py312-django42
          - python-version: '3.13'
            requirements: django_4_2
            tox_env: py313-django42

          - python-version: '3.10'
            requirements: django_5_1
            tox_env: py310-django51
          - python-version: '3.11'
            requirements: django_5_1
            tox_env: py311-django51
          - python-version: '3.12'
            requirements: django_5_1
            tox_env: py312-django51
          - python-version: '3.13'
            requirements: django_5_1
            tox_env: py313-django51

          - python-version: '3.10'
            requirements: django_5_2
            tox_env: py310-django52
          - python-version: '3.11'
            requirements: django_5_2
            tox_env: py311-django52
          - python-version: '3.12'
            requirements: django_5_2
            tox_env: py312-django52
          - python-version: '3.13'
            requirements: django_5_2
            tox_env: py313-django52

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip compile pyproject.toml examples/requirements/${{ matrix.requirements }}.in --all-extras -o examples/requirements/${{ matrix.requirements }}.txt 
        pip install -r examples/requirements/${{ matrix.requirements }}.txt
        uv pip compile pyproject.toml examples/requirements/test.in --all-extras -o examples/requirements/test.txt
        pip install -r examples/requirements/test.txt
    - name: List Dependencies
      run: |
        pip list
    - name: Run Tests
      run: tox -e ${{ matrix.tox_env }}
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Run Tests

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: True
